# Nome da aplicacao
spring.application.name=SisReserva

# Configuracoes do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:sisreservadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuracao do Hibernate / JPA
# O 'update' faz o Spring ler suas classes Java e criar as tabelas no banco automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Habilitar o console do H2 no navegador para vermos as tabelas fisicamente
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console